# Generated by Django 4.1 on 2022-09-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verge_ids', models.IntegerField(max_length=20, verbose_name='verge_ids')),
            ],
        ),
        migrations.CreateModel(
            name='Verge_data',
            fields=[
                ('verge_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraperapp.article_ids')),
                ('https_links', models.CharField(max_length=510, verbose_name='https_links')),
                ('verge_articles', models.CharField(max_length=510, verbose_name='verge_articles')),
                ('verge_authors', models.CharField(max_length=100, verbose_name='verge_authors')),
                ('article_dates', models.DateField(max_length=20, verbose_name='article_dates')),
            ],
        ),
    ]
